# @package eval.tofu
# NOTE: the above line is not a comment, but sets the package for config. See https://hydra.cc/docs/upgrades/0.11_to_1.0/adding_a_package_directive/

defaults: # include all defined metrics files
  - tofu_metrics: 
    # utility
    - model_utility
    - forget_Q_A_gibberish
    #memorization
    - extraction_strength
    - exact_memorization
    - forget_Q_A_PARA_Prob
    - forget_Truth_Ratio
    #privacy
    - mia_min_k_plus_plus
    - mia_min_k
    - mia_loss
    - mia_zlib


handler: TOFUEvaluator
output_dir: ${paths.output_dir} # set to default eval directory
metrics: {} # lists a mapping from each evaluation metric to its config 
# populated through the first (@package) line in each metric config
overwrite: false
forget_split: forget10
holdout_split: holdout10
retain_logs_path: null
question_key: "question" # Specifies which key to use during forget and retain evaluations (e.g., "question" or "paraphrased_question")
batch_size: 25